#!/usr/bin/perl

#
# Copyright (C) 2013 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use strict;
use esmith::Build::CreateLinks  qw(:all);

#
# Event nethserver-ipsec-update
#
event_actions('nethserver-ipsec-update', qw( 
    initialize-default-databases 00
    nethserver-ipsec-synchronize-nssdb 30
));

event_templates('nethserver-ipsec-update', qw(
    /etc/ipsec.d/tunnels.conf
    /etc/ipsec.d/l2tp.conf
    /etc/ipsec.d/tunnels.secrets
    /etc/xl2tpd/xl2tpd.conf
    /etc/ppp/options.xl2tpd
    /etc/ipsec.d/nsspassword
));

event_services('nethserver-ipsec-update', qw(
    ipsec restart
    xl2tpd restart
    rsyslog restart
));

#
# Event nethserver-ipsec-save
#
event_templates('nethserver-ipsec-save', qw(
    /etc/ipsec.d/tunnels.conf
    /etc/ipsec.d/l2tp.conf
    /etc/ipsec.d/tunnels.secrets
    /etc/xl2tpd/xl2tpd.conf
    /etc/ppp/options.xl2tpd
));

event_services('nethserver-ipsec-save', qw(
    ipsec restart
    xl2tpd restart
));

event_actions('nethserver-ipsec-save', qw(
    firewall-adjust 40
    trusted-networks-modify 95
));

#
# Event certificate-update 
#
event_actions('certificate-update', qw(
    nethserver-ipsec-synchronize-nssdb 30
));


#
# Event nethserver-samba-save
#
event_actions('nethserver-samba-save', qw(
   nethserver-ipsec-synchronize-l2tpusers 97
));


#
# Event nethserver-vpn-save
#
event_actions('nethserver-vpn-save', qw(
   nethserver-ipsec-synchronize-l2tpusers 30   
));


#
# FIXME event runlevel-adjust
#
event_actions('runlevel-adjust', qw(
    nethserver-ipsec-synchronize-l2tpusers 98
));

