#!/usr/bin/perl

use JSON;
use esmith::ConfigDB;

my $db = esmith::ConfigDB->open("vpn") || die("Could not open VPN DB");

foreach my $tunnel ($db->get_all_by_prop('type' => 'ipsec-tunnel')) {
    my $leftid =  $tunnel->prop('leftid') || "";
    my $rightid =  $tunnel->prop('rightid') || "";
    if ($leftid ne "" && $rightid ne "") {
        next;
    }

    $tunnel->set_prop('leftid',$tunnel->prop('left'));
    $tunnel->set_prop('rightid',$tunnel->prop('right'));
}

